### ISSUE TITLE
Incorrect price option added when a default is set

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-wish-lists#31]
From a customer:

>>>If a download has price variations and one of them was set to be the default option, when add options to wish list, no matter whether the default option is selected or not, it will always be appended to the list, making items added to wish list are always one more than what it should be.

**Comment by mindctrl** [comment]
This only appears to happen when multiple purchase forms are on the page. Attached PR prevents it from checking all purchase forms on the page.

**Comment by pippinsplugins** [comment]
Looks good!
