### ISSUE TITLE
Add Classes to Titles

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/edd-wish-lists#35]
Lots of `h3`s around with no way to target them. Classes on them would be helpful, our wrapping any output in a wishlist-specific div.

**Comment by mindctrl** [comment]
@spencerfinnell something like this on all the `<h3>` suit you `<h3 class="edd-wish-list-heading">`? Or would you rather have a little more context, like `<h3 class="edd-wish-list-edit-heading">` for the various types of views?

**Comment by sumobi** [comment]
@spencerfinnell @mindctrl I like the idea of wrapping a div around each view with a class, before and after the `edd_wl_load_template` call. That way it doesn't affect the template files and allows easier targeting of other elements.

**Comment by spencerfinnell** [comment]
Put both classes on the title. A base one and the current view.

**Comment by sumobi** [comment]
Closed via https://github.com/easydigitaldownloads/edd-wish-lists/commit/2a4f33250e6a3b90eca1e7df0350cedef92ac26a
