### ISSUE TITLE
Wish List doesn't work on Recommended Products on checkout page

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-wish-lists#38]
The 'Add to Wish List' button gets added to the Recommended Products display on the checkout page, but it doesn't work because the javascript doesn't get loaded there.

**Comment by mindctrl** [comment]
I'm wondering if we should just disable the wish list button instead. Recommended Products, Cross-sell Upsell, and Recently Viewed Items can all show items on the checkout. So can any other number of themes and extensions. Thoughts here @cklosowski?

**Comment by sumobi** [comment]
@mindctrl I agree with that, I don't see any need for adding downloads to a wish list from the checkout page.

**Comment by mindctrl** [comment]
@sumobi sounds good to me. Will close this.

**Comment by mindctrl** [comment]
Derp. Meant to say will close after disabling on checkout.
