### ISSUE TITLE
More accurate css selectors

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/edd-wish-lists#45]
My theme use glyphicons and your selector overrides him:

```
.glyphicon {
    font-family: edd-wish-lists;
...
}
```

A solution could be use `.edd-wl-button .glyphicon` instead

**Comment by sumobi** [comment]
👍  Thanks, we'll look into it

**Comment by rubengc** [comment]
Do you want a PR with this?

**Comment by pippinsplugins** [comment]
Pr would be great!

**Comment by rubengc** [comment]
Has PR

**Comment by sumobi** [comment]
Added via https://github.com/easydigitaldownloads/edd-wish-lists/commit/f98f5ad8395ce2f34d6122177cff8dcf152718b8
