### ISSUE TITLE
Wish Lists section shows up in menu editor

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-wish-lists#47]
I could definitely be wrong, but I'm almost positive there's no reason for the Wish Lists post type to show up here: 

![screen shot 2016-08-11 at 8 50 24 pm](https://cloud.githubusercontent.com/assets/2359131/17612321/6c5ccd26-6005-11e6-8bfc-5d3f1229af3b.png)

And of course it can't be used so there's no functionality or anything. According to the Codex, `show_in_nav_menus`'s default value is `false`, which should keep it from showing up there. Adding that to the args removes it properly, so perhaps the default has changed.

Forgive me if I'm missing something. I'll wait for feedback before submitting code.

**Comment by pippinsplugins** [comment]
Let's add `'show_in_nav_menus' => false`

**Comment by SDavisMedia** [comment]
Done.

**Comment by pippinsplugins** [comment]
@SDavisMedia go ahead and version bump and deploy an update please.

**Comment by SDavisMedia** [comment]
You got it.
