### ISSUE TITLE
Turn EDD Wish Lists in a plugin for general purpose lists

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/edd-wish-lists#49]
Hi @sumobi 

I test more in deep this plugin and is fantastic to generate downloads list 

I have great plans with this plugins, for this I would like to propose you a change turning EDD Wish Lists into EDD Downloads Lists(a concept more general of lists) and turn wish lists into a plugin (like EDD Favorites)

What features gains with this change?
- Turn this plugin into a more general purpose
- Separating wish list in one list gives us the possibility to use this list for promotional purposes as send an email to users that have a download in their wish list (and not in favorites, or a list where user want his favourites downloads of a category)

My plans are create a user public profile plugin with widgets that could use your lists to show, user favourites, user wish list, and the rest of lists as user collections or something like that

What do you think?

**Comment by sumobi** [comment]
It would need to be a seperate plugin. There are many customers who already use EDD Wish Lists so changing the plugin in such a big way is not something we can do.

**Comment by rubengc** [comment]
Ok, anyway thanks!

I will work on this, I'll let you know when the repo is available

**Comment by rubengc** [comment]
Hi @sumobi 

I have published a in development repository about features mentioned here:
https://github.com/rubengc/edd-downloads-lists

I will need some help with this plugin, so your contribution will be awesome :)

ping to @pippinsplugins
