### ISSUE TITLE
[Hook Request]edd_wl_query_args filter

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/edd-wish-lists#50]
Hi!

I propose add a filter (edd_wl_query_args) on function edd_wl_get_query( $status ) (functions.php L:374) to allow other plugins filter default wish list query arguments

Usage examples:
Basically I have two pages (one from EDD WL and another one to EDD Favorites) and user could add/remove downloads on their list, I want to filter this query on EDD WL lists to prevent show this EDD Favorites list
Other example is that I am building a plugin to add multiple lists (like EDD Favorites) where you could set all lists that you want (for example, likes, favorites, wishes, recommendations, etc) and I want to remove all lists defined here on the main lists generated from EDD WL (is an extension so I do not want to override your template)

Code (functions.php after line 404, when you set wl_token and before WP_Query call):
```php
$query = apply_filters( 'edd_wl_query_args', $query );
```

I could create a PR with this if you like the idea

**Comment by pippinsplugins** [comment]
A PR would be great!

**Comment by rubengc** [comment]
Has PR

**Comment by sumobi** [comment]
Added via https://github.com/easydigitaldownloads/edd-wish-lists/commit/f98f5ad8395ce2f34d6122177cff8dcf152718b8
