### ISSUE TITLE
PHP 7.1.3: Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-wish-lists#57]
In PHP 7.1.3, I am seeing this warning when viewing a product:

`Warning: A non-numeric value encountered in /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/edd-wish-lists/includes/template-functions.php on line 202`

**Comment by pippinsplugins** [comment]
@mintplugins try again on `master`?

**Comment by mintplugins** [comment]
Working great now! 👍
