### ISSUE TITLE
Missing close button icons

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-wish-lists#58]
The close button isn't appearing on any of the modal popups. Should be shown in the top right corner.

<img width="678" alt="screen shot 2017-06-17 at 8 53 59 pm" src="https://user-images.githubusercontent.com/52581/27251643-2859e382-539f-11e7-91e2-fe9ff1365a76.png">

Looks like it's missing a CSS class, `edd-wl-button`.

<img width="660" alt="screen shot 2017-06-17 at 8 56 10 pm" src="https://user-images.githubusercontent.com/52581/27251653-6febd322-539f-11e7-9922-9db0da344c61.png">

**Comment by amdrew** [comment]
Ready for testing https://github.com/easydigitaldownloads/edd-wish-lists/pull/59

**Comment by pippinsplugins** [comment]
Looks good.
