### ISSUE TITLE
Wish list buttons don't do anything on EDD taxonomy archive pages

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-wish-lists#60]
Wish lists has never outputted its scripts onto any custom taxonomy archive pages, only the [downloads] shortcode or the single download page. As a result, if a theme has included a download grid on `taxonomy-download_category.php` or `taxonomy-download_tag.php`, which in turn outputs the wish list buttons then they don't do anything.

**Comment by amdrew** [comment]
@easydigitaldownloads/core-devs Ready for testing https://github.com/easydigitaldownloads/edd-wish-lists/pull/61

**Comment by amdrew** [comment]
Should also be loaded on the custom post type archive page, just in case the theme outputs a download grid there. Added `is_post_type_archive( 'download' )`.

**Comment by pippinsplugins** [comment]
Looks good, merged.
