### ISSUE TITLE
PHP Fatal error:  Uncaught Error: [] operator not supported for strings

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-wish-lists#62]
Using PHP 7.1.1, the following message appears when clicking add to wish list.

```
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /wp-content/plugins/edd-wish-lists/includes/ajax-functions.php:241
```

Looks like `$items` should have been declared as a blank array, not a string:
https://github.com/easydigitaldownloads/edd-wish-lists/blob/master/includes/ajax-functions.php#L228

**Comment by amdrew** [comment]
@easydigitaldownloads/core-devs Ready for testing https://github.com/easydigitaldownloads/edd-wish-lists/pull/63.

Tested with PHP 5.6.30 and 7.1.1

**Comment by pippinsplugins** [comment]
Merged and deploying update.
